/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Luke Steel (https://sketchfab.com/luke.steel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crossroads-6eba14662bd048f9bc1ca10e63b5622f
Title: Crossroads
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three"

import crossroadsScene from '../assets/3d/crossroads.glb'



const Model = (props) => {
    const crossroadsRef = useRef();
    const { nodes, materials } = useGLTF(crossroadsScene);

    return (
        <a.group ref={crossroadsRef} {...props} dispose={null}>

            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    geometry={nodes.Object_2.geometry}
                    material={materials.Back1Mtl}
                />
                <mesh
                    geometry={nodes.Object_3.geometry}
                    material={materials.Back2Mtl}
                />
                <mesh
                    geometry={nodes.Object_4.geometry}
                    material={materials.Ball1Mtl}
                />
                <mesh
                    geometry={nodes.Object_5.geometry}
                    material={materials.Ball1Mtl}
                />
                <mesh
                    geometry={nodes.Object_6.geometry}
                    material={materials.Ball1Mtl}
                />
                <mesh
                    geometry={nodes.Object_7.geometry}
                    material={materials.Ball1Mtl}
                />
                <mesh
                    geometry={nodes.Object_8.geometry}
                    material={materials.Ball1Mtl}
                />
                <mesh
                    geometry={nodes.Object_9.geometry}
                    material={materials.Battlearmor1Mtl}
                />
                <mesh
                    geometry={nodes.Object_10.geometry}
                    material={materials.Battlearmor1Mtl}
                />
                <mesh
                    geometry={nodes.Object_11.geometry}
                    material={materials.Block15Mtl}
                />
                <mesh
                    geometry={nodes.Object_12.geometry}
                    material={materials.Block1Mtl}
                />
                <mesh
                    geometry={nodes.Object_13.geometry}
                    material={materials.Center1Mtl}
                />
                <mesh
                    geometry={nodes.Object_14.geometry}
                    material={materials.Center2Mtl}
                />
                <mesh
                    geometry={nodes.Object_15.geometry}
                    material={materials.Center3Mtl}
                />
                <mesh
                    geometry={nodes.Object_16.geometry}
                    material={materials.Center4Mtl}
                />
                <mesh
                    geometry={nodes.Object_17.geometry}
                    material={materials.Pillar2Mtl}
                />
                <mesh
                    geometry={nodes.Object_18.geometry}
                    material={materials.RightPath1Mtl}
                />
                <mesh
                    geometry={nodes.Object_19.geometry}
                    material={materials.SmoothBlockModel1306Mtl}
                />
                <mesh
                    geometry={nodes.Object_20.geometry}
                    material={materials.SmoothBlockModel1499Mtl}
                />
                <mesh
                    geometry={nodes.Object_21.geometry}
                    material={materials.SmoothBlockModel1505Mtl}
                />
                <mesh
                    geometry={nodes.Object_22.geometry}
                    material={materials.SmoothBlockModel1511Mtl}
                />
                <mesh
                    geometry={nodes.Object_23.geometry}
                    material={materials.SmoothBlockModel1517Mtl}
                />
                <mesh
                    geometry={nodes.Object_24.geometry}
                    material={materials.SmoothBlockModel16Mtl}
                />
                <mesh
                    geometry={nodes.Object_25.geometry}
                    material={materials.SmoothBlockModel18Mtl}
                />
                <mesh
                    geometry={nodes.Object_26.geometry}
                    material={materials.SmoothBlockModel1Mtl}
                />
                <mesh
                    geometry={nodes.Object_27.geometry}
                    material={materials.SmoothBlockModel2Mtl}
                />
                <mesh
                    geometry={nodes.Object_28.geometry}
                    material={materials.SmoothBlockModel38Mtl}
                />
                <mesh
                    geometry={nodes.Object_29.geometry}
                    material={materials.SmoothBlockModel3Mtl}
                />
                <mesh
                    geometry={nodes.Object_30.geometry}
                    material={materials.SmoothBlockModel3Mtl}
                />
                <mesh
                    geometry={nodes.Object_31.geometry}
                    material={materials.SmoothBlockModel402Mtl}
                />
                <mesh
                    geometry={nodes.Object_32.geometry}
                    material={materials.SmoothBlockModel402Mtl}
                />
                <mesh
                    geometry={nodes.Object_33.geometry}
                    material={materials.SmoothBlockModel402Mtl}
                />
                <mesh
                    geometry={nodes.Object_34.geometry}
                    material={materials.SmoothBlockModel402Mtl}
                />
                <mesh
                    geometry={nodes.Object_35.geometry}
                    material={materials.SmoothBlockModel402Mtl}
                />
                <mesh
                    geometry={nodes.Object_36.geometry}
                    material={materials.SmoothBlockModel409Mtl}
                />
                <mesh
                    geometry={nodes.Object_37.geometry}
                    material={materials.SmoothBlockModel413Mtl}
                />
                <mesh
                    geometry={nodes.Object_38.geometry}
                    material={materials.SmoothBlockModel518Mtl}
                />
                <mesh
                    geometry={nodes.Object_39.geometry}
                    material={materials.SmoothBlockModel53Mtl}
                />
                <mesh
                    geometry={nodes.Object_40.geometry}
                    material={materials.SmoothBlockModel546Mtl}
                />
                <mesh
                    geometry={nodes.Object_41.geometry}
                    material={materials.SmoothBlockModel57Mtl}
                />
                <mesh
                    geometry={nodes.Object_42.geometry}
                    material={materials.SmoothBlockModel57Mtl}
                />
                <mesh
                    geometry={nodes.Object_43.geometry}
                    material={materials.SmoothBlockModel58Mtl}
                />
                <mesh
                    geometry={nodes.Object_44.geometry}
                    material={materials.SmoothBlockModel58Mtl}
                />
                <mesh
                    geometry={nodes.Object_45.geometry}
                    material={materials.SmoothBlockModel646Mtl}
                />
                <mesh
                    geometry={nodes.Object_46.geometry}
                    material={materials.SmoothBlockModel646Mtl}
                />
                <mesh
                    geometry={nodes.Object_47.geometry}
                    material={materials.SmoothBlockModel649Mtl}
                />
                <mesh
                    geometry={nodes.Object_48.geometry}
                    material={materials.SmoothBlockModel680Mtl}
                />
                <mesh
                    geometry={nodes.Object_49.geometry}
                    material={materials.SmoothBlockModel680Mtl}
                />
                <mesh
                    geometry={nodes.Object_50.geometry}
                    material={materials.SmoothBlockModel681Mtl}
                />
                <mesh
                    geometry={nodes.Object_51.geometry}
                    material={materials.SmoothBlockModel793Mtl}
                />
                <mesh
                    geometry={nodes.Object_52.geometry}
                    material={materials.SmoothBlockModel807Mtl}
                />
                <mesh
                    geometry={nodes.Object_53.geometry}
                    material={materials.SmoothBlockModel809Mtl}
                />
                <mesh
                    geometry={nodes.Object_54.geometry}
                    material={materials.SmoothBlockModel860Mtl}
                />
                <mesh
                    geometry={nodes.Object_55.geometry}
                    material={materials.SmoothBlockModel883Mtl}
                />
                <mesh
                    geometry={nodes.Object_56.geometry}
                    material={materials.Spawnlocation2Mtl}
                />
            </group>
        </a.group>
    );
}

export default Model;